### ISSUE TITLE
Holder wallet android app

### ISSUE THREAD

**Issue by Munguajuna** [HODLERTECH/HODLER-Android-Multi-Asset-Wallet#69]
So far so good!  Some issues are there can't add tokens automatically!  When add via manually, some of the tokens with 8 decimal, show 18 decimal when I want to send them..! No place to correct decimal..

**Comment by HODLERTECH** [comment]
Thank you. We have checked audo-adding and working well, video: https://hodler.tech/manuals/tokanadd.mp4
Pay attention to the Tobiasz Horodko Token  and Bagden Token.

Could you tell us which token do not working for you?

**Comment by Munguajuna** [comment]
hello!
I can't L- PESA KRIPTON (LPK) automatically..!  I added it manually and
deposited some amounts but when I want to decimal,  it brings me 18decimal
while the token has 8decimal

**Comment by DanielMazurFL4RE** [comment]
Your token has these 8 decimals, but due to bug it displays ETHEREUM decimals (18) in transaction details. You can transfer your token with good amount of decimals, 18 will be shown only in tx details and it does not matter for transaction. This bug is already fixed and will be included in next release of application
